Add start/end dates for training period
equinor/gordo-components pull request #23
Opened 2018-11-06 12:12 UTC by Natalie-Caruana

Need to check why unit test fails

2018-11-10 20:02 UTC, epa095 requested changes
looks good besides somethings minor.

2018-11-13 12:47 UTC, epa095 requested changes

2018-11-13 14:23 UTC, epa095 approved these changes

2018-11-13 14:30 UTC, epa095 requested changes

2018-11-15 14:42 UTC, flikka requested changes
Test that fails can be fixed by adding the TIME_FROM/TO env variables to the test, but we need to decide if we want these "data about the data" to be in an undetermined amount of env variables, or put into a data_config object. I lean towards the latter.

2018-11-16 10:06 UTC, closed without merging